In [500]:
%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.utils import resample
from sklearn.feature_selection import SelectFromModel
from xgboost import XGBClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report,roc_auc_score ,accuracy_score, confusion_matrix, recall_score, precision_score,f1_score
import warnings
warnings.filterwarnings('ignore')
color = sns.color_palette()[3]

In [71]:
data = pd.read_csv("zomato.csv")
data.head()

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari
2,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari
3,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari
4,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari

In [303]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51717 entries, 0 to 51716
Data columns (total 17 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   url                          51717 non-null  object
 1   address                      51717 non-null  object
 2   name                         51717 non-null  object
 3   online_order                 51717 non-null  object
 4   book_table                   51717 non-null  object
 5   rate                         43942 non-null  object
 6   votes                        51717 non-null  int64
 7   phone                        50509 non-null  object
 8   location                     51696 non-null  object
 9   rest_type                    51490 non-null  object
 10  dish_liked                   23639 non-null  object
 11  cuisines                     51672 non-null  object
 12  approx_cost(for two people)  51371 non-null  object
 13  reviews_list                 51717 non-null  object
 14  menu_item                    51717 non-null  object
 15  listed_in(type)              51717 non-null  object
 16  listed_in(city)              51717 non-null  object
dtypes: int64(1), object(16)
memory usage: 6.7+ MB

In [566]:
df = data.drop(columns=['name','url','phone','votes','reviews_list','address'], axis = 1)
(df.isnull().sum()*100)/len(df)

online_order                    0.000000
book_table                      0.000000
rate                           15.033741
location                        0.040606
rest_type                       0.438927
dish_liked                     54.291626
cuisines                        0.087012
approx_cost(for two people)     0.669026
menu_item                       0.000000
listed_in(type)                 0.000000
listed_in(city)                 0.000000
dtype: float64

In [567]:
df.nunique()

online_order                      2
book_table                        2
rate                             64
location                         93
rest_type                        93
dish_liked                     5271
cuisines                       2723
approx_cost(for two people)      70
menu_item                      9098
listed_in(type)                   7
listed_in(city)                  30
dtype: int64

In [568]:
df.drop(columns=['dish_liked'], axis = 1,inplace = True)

In [569]:
df.dropna(inplace = True)

In [570]:
df['rate'] = df2["rate"].str.split("/", expand = False).str[0]
df = df[(df['rate'] != 'NEW') & (df['rate'] != '-')]
df['rate']= df['rate'].astype(float)
df['rate']=df['rate'].apply(lambda x : 1 if x >=3.7 else 0)
#(df['rate'].value_counts()*100)/len(df)

In [571]:
df['rest_type1']=df['rest_type'].str.split(',').str[0].str.strip()
df['rest_type2']=df['rest_type'].str.split(',').str[1].str.strip()
df.drop(columns=['rest_type'],inplace=True)

In [572]:
df['cuisines'].value_counts()
df['total_cuisines']=df['cuisines'].astype(str).apply(lambda x: len(x.split(',')))
df.drop(columns=['cuisines'],inplace=True)

In [573]:
#df['listed_in(type)'].value_counts()
#df['listed_in(city)'].value_counts()

In [574]:
#df['total_items']=df['menu_item'].astype(str).apply(lambda x: len(x.split(',')))
len(df[df['menu_item']=='[]'])
df.drop(columns=['menu_item'],inplace=True)

In [575]:
df['approx_cost'] = df['approx_cost(for two people)'].astype(str).apply(lambda x: x.replace(',', ''))
df['approx_cost'] = df['approx_cost'].astype(float)
df.drop(['approx_cost(for two people)'], axis=1, inplace=True)

In [580]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 41263 entries, 0 to 51716
Data columns (total 32 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   online_order     41263 non-null  int64
 1   book_table       41263 non-null  int64
 2   rate             41263 non-null  int64
 3   location         41263 non-null  int32
 4   listed_in(type)  41263 non-null  int32
 5   listed_in(city)  41263 non-null  int32
 6   total_cuisines   41263 non-null  int64
 7   approx_cost      41263 non-null  float64
 8   Bakery           41263 non-null  uint8
 9   Bar              41263 non-null  uint8
 10  Beverage Shop    41263 non-null  uint8
 11  Bhojanalya       41263 non-null  uint8
 12  Cafe             41263 non-null  uint8
 13  Casual Dining    41263 non-null  uint8
 14  Club             41263 non-null  uint8
 15  Confectionery    41263 non-null  uint8
 16  Delivery         41263 non-null  uint8
 17  Dessert Parlor   41263 non-null  uint8
 18  Dhaba            41263 non-null  uint8
 19  Fine Dining      41263 non-null  uint8
 20  Food Court       41263 non-null  uint8
 21  Food Truck       41263 non-null  uint8
 22  Irani Cafee      41263 non-null  uint8
 23  Kiosk            41263 non-null  uint8
 24  Lounge           41263 non-null  uint8
 25  Meat Shop        41263 non-null  uint8
 26  Mess             41263 non-null  uint8
 27  Microbrewery     41263 non-null  uint8
 28  Pub              41263 non-null  uint8
 29  Quick Bites      41263 non-null  uint8
 30  Sweet Shop       41263 non-null  uint8
 31  Takeaway         41263 non-null  uint8
dtypes: float64(1), int32(3), int64(4), uint8(24)
memory usage: 4.3 MB

In [577]:
df = df.join(pd.get_dummies(df.filter(like='rest_type').stack()).groupby(level=0).max())
df.drop(columns=['rest_type1','rest_type2'],inplace=True)
df['online_order'] = df['online_order'].map({'Yes': 1, 'No': 0})
df['book_table'] = df['book_table'].map({'Yes': 1, 'No': 0})

In [578]:
le = LabelEncoder()
df['location'] = le.fit_transform(df['location'])
df['listed_in(type)'] = le.fit_transform(df['listed_in(type)'])
df['listed_in(city)'] = le.fit_transform(df['listed_in(city)'])

In [579]:
df.head()

,online_order,book_table,rate,location,listed_in(type),listed_in(city),total_cuisines,approx_cost,Bakery,Bar,...,Irani Cafee,Kiosk,Lounge,Meat Shop,Mess,Microbrewery,Pub,Quick Bites,Sweet Shop,Takeaway
0,1,1,1,1,0,1,3,800.0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,0,1,1,0,1,3,800.0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,1,1,0,1,3,800.0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,1,1,0,1,2,300.0,0,0,...,0,0,0,0,0,0,0,1,0,0
4,0,0,1,4,0,1,2,600.0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [548]:
x = df.drop('rate', axis=1)
y = df['rate']
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=420,stratify=y)

In [549]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.fit_transform(x_test)

In [550]:
models = {
    'LogisticRegression' : LogisticRegression(),
    'DecisionTreeClassifier' : DecisionTreeClassifier(),
    'XGBoost':XGBClassifier(),
    'KNeighborsClassifier' : KNeighborsClassifier(),
    'RandomForestClassifier' : RandomForestClassifier(),
}
print('=======================')
print('==       Data        ==')
print('=======================')
for name,model in models.items():
    model.fit(x_train, y_train)
    y_pred = model.predict(x_test)
    print('\n=======================')
    print(name,'\n=======================')
    print('\t      Accurcy : ',accuracy_score(y_test, y_pred))
    print(classification_report(y_test, y_pred),'\n')
    print('\n------------------------------------------')

=======================
==       Data        ==
=======================

=======================
LogisticRegression
=======================
	      Accurcy :  0.6861620486307456
              precision    recall  f1-score   support

           0       0.62      0.64      0.63      5213
           1       0.73      0.72      0.73      7166

    accuracy                           0.69     12379
   macro avg       0.68      0.68      0.68     12379
weighted avg       0.69      0.69      0.69     12379



------------------------------------------

=======================
DecisionTreeClassifier
=======================
	      Accurcy :  0.80442685192665
              precision    recall  f1-score   support

           0       0.75      0.79      0.77      5213
           1       0.84      0.81      0.83      7166

    accuracy                           0.80     12379
   macro avg       0.80      0.80      0.80     12379
weighted avg       0.81      0.80      0.81     12379



------------------------------------------

=======================
XGBoost
=======================
	      Accurcy :  0.7580580014540754
              precision    recall  f1-score   support

           0       0.71      0.73      0.72      5213
           1       0.80      0.78      0.79      7166

    accuracy                           0.76     12379
   macro avg       0.75      0.75      0.75     12379
weighted avg       0.76      0.76      0.76     12379



------------------------------------------

=======================
KNeighborsClassifier
=======================
	      Accurcy :  0.7023992244930931
              precision    recall  f1-score   support

           0       0.65      0.64      0.64      5213
           1       0.74      0.75      0.74      7166

    accuracy                           0.70     12379
   macro avg       0.69      0.69      0.69     12379
weighted avg       0.70      0.70      0.70     12379



------------------------------------------

=======================
RandomForestClassifier
=======================
	      Accurcy :  0.7877857662169804
              precision    recall  f1-score   support

           0       0.75      0.75      0.75      5213
           1       0.82      0.82      0.82      7166

    accuracy                           0.79     12379
   macro avg       0.78      0.78      0.78     12379
weighted avg       0.79      0.79      0.79     12379



------------------------------------------

In [556]:
params = { 
    'max_depth' : [10,50,None],
    'criterion' :['gini', 'entropy','log_loss'],
    'splitter':['best', 'random']
}

grid_search = GridSearchCV(DecisionTreeClassifier(), param_grid=params, scoring = 'accuracy', cv = 5, verbose=2)
grid_search.fit(x_train, y_train)

Fitting 5 folds for each of 18 candidates, totalling 90 fits
[CV] END ........criterion=gini, max_depth=10, splitter=best; total time=   0.0s
[CV] END ........criterion=gini, max_depth=10, splitter=best; total time=   0.0s
[CV] END ........criterion=gini, max_depth=10, splitter=best; total time=   0.0s
[CV] END ........criterion=gini, max_depth=10, splitter=best; total time=   0.0s
[CV] END ........criterion=gini, max_depth=10, splitter=best; total time=   0.0s
[CV] END ......criterion=gini, max_depth=10, splitter=random; total time=   0.0s
[CV] END ......criterion=gini, max_depth=10, splitter=random; total time=   0.0s
[CV] END ......criterion=gini, max_depth=10, splitter=random; total time=   0.0s
[CV] END ......criterion=gini, max_depth=10, splitter=random; total time=   0.0s
[CV] END ......criterion=gini, max_depth=10, splitter=random; total time=   0.0s
[CV] END ........criterion=gini, max_depth=50, splitter=best; total time=   0.0s
[CV] END ........criterion=gini, max_depth=50, splitter=best; total time=   0.0s
[CV] END ........criterion=gini, max_depth=50, splitter=best; total time=   0.0s
[CV] END ........criterion=gini, max_depth=50, splitter=best; total time=   0.0s
[CV] END ........criterion=gini, max_depth=50, splitter=best; total time=   0.0s
[CV] END ......criterion=gini, max_depth=50, splitter=random; total time=   0.0s
[CV] END ......criterion=gini, max_depth=50, splitter=random; total time=   0.0s
[CV] END ......criterion=gini, max_depth=50, splitter=random; total time=   0.0s
[CV] END ......criterion=gini, max_depth=50, splitter=random; total time=   0.0s
[CV] END ......criterion=gini, max_depth=50, splitter=random; total time=   0.0s
[CV] END ......criterion=gini, max_depth=None, splitter=best; total time=   0.0s
[CV] END ......criterion=gini, max_depth=None, splitter=best; total time=   0.0s
[CV] END ......criterion=gini, max_depth=None, splitter=best; total time=   0.0s
[CV] END ......criterion=gini, max_depth=None, splitter=best; total time=   0.0s
[CV] END ......criterion=gini, max_depth=None, splitter=best; total time=   0.0s
[CV] END ....criterion=gini, max_depth=None, splitter=random; total time=   0.0s
[CV] END ....criterion=gini, max_depth=None, splitter=random; total time=   0.0s
[CV] END ....criterion=gini, max_depth=None, splitter=random; total time=   0.0s
[CV] END ....criterion=gini, max_depth=None, splitter=random; total time=   0.0s
[CV] END ....criterion=gini, max_depth=None, splitter=random; total time=   0.0s
[CV] END .....criterion=entropy, max_depth=10, splitter=best; total time=   0.0s
[CV] END .....criterion=entropy, max_depth=10, splitter=best; total time=   0.0s
[CV] END .....criterion=entropy, max_depth=10, splitter=best; total time=   0.0s
[CV] END .....criterion=entropy, max_depth=10, splitter=best; total time=   0.0s
[CV] END .....criterion=entropy, max_depth=10, splitter=best; total time=   0.0s
[CV] END ...criterion=entropy, max_depth=10, splitter=random; total time=   0.0s
[CV] END ...criterion=entropy, max_depth=10, splitter=random; total time=   0.0s
[CV] END ...criterion=entropy, max_depth=10, splitter=random; total time=   0.0s
[CV] END ...criterion=entropy, max_depth=10, splitter=random; total time=   0.0s
[CV] END ...criterion=entropy, max_depth=10, splitter=random; total time=   0.0s
[CV] END .....criterion=entropy, max_depth=50, splitter=best; total time=   0.0s
[CV] END .....criterion=entropy, max_depth=50, splitter=best; total time=   0.0s
[CV] END .....criterion=entropy, max_depth=50, splitter=best; total time=   0.0s
[CV] END .....criterion=entropy, max_depth=50, splitter=best; total time=   0.0s
[CV] END .....criterion=entropy, max_depth=50, splitter=best; total time=   0.0s
[CV] END ...criterion=entropy, max_depth=50, splitter=random; total time=   0.0s
[CV] END ...criterion=entropy, max_depth=50, splitter=random; total time=   0.0s
[CV] END ...criterion=entropy, max_depth=50, splitter=random; total time=   0.0s
[CV] END ...criterion=entropy, max_depth=50, splitter=random; total time=   0.0s
[CV] END ...criterion=entropy, max_depth=50, splitter=random; total time=   0.0s
[CV] END ...criterion=entropy, max_depth=None, splitter=best; total time=   0.0s
[CV] END ...criterion=entropy, max_depth=None, splitter=best; total time=   0.0s
[CV] END ...criterion=entropy, max_depth=None, splitter=best; total time=   0.0s
[CV] END ...criterion=entropy, max_depth=None, splitter=best; total time=   0.0s
[CV] END ...criterion=entropy, max_depth=None, splitter=best; total time=   0.0s
[CV] END .criterion=entropy, max_depth=None, splitter=random; total time=   0.0s
[CV] END .criterion=entropy, max_depth=None, splitter=random; total time=   0.0s
[CV] END .criterion=entropy, max_depth=None, splitter=random; total time=   0.0s
[CV] END .criterion=entropy, max_depth=None, splitter=random; total time=   0.0s
[CV] END .criterion=entropy, max_depth=None, splitter=random; total time=   0.0s
[CV] END ....criterion=log_loss, max_depth=10, splitter=best; total time=   0.0s
[CV] END ....criterion=log_loss, max_depth=10, splitter=best; total time=   0.0s
[CV] END ....criterion=log_loss, max_depth=10, splitter=best; total time=   0.0s
[CV] END ....criterion=log_loss, max_depth=10, splitter=best; total time=   0.0s
[CV] END ....criterion=log_loss, max_depth=10, splitter=best; total time=   0.0s
[CV] END ..criterion=log_loss, max_depth=10, splitter=random; total time=   0.0s
[CV] END ..criterion=log_loss, max_depth=10, splitter=random; total time=   0.0s
[CV] END ..criterion=log_loss, max_depth=10, splitter=random; total time=   0.0s
[CV] END ..criterion=log_loss, max_depth=10, splitter=random; total time=   0.0s
[CV] END ..criterion=log_loss, max_depth=10, splitter=random; total time=   0.0s
[CV] END ....criterion=log_loss, max_depth=50, splitter=best; total time=   0.0s
[CV] END ....criterion=log_loss, max_depth=50, splitter=best; total time=   0.0s
[CV] END ....criterion=log_loss, max_depth=50, splitter=best; total time=   0.0s
[CV] END ....criterion=log_loss, max_depth=50, splitter=best; total time=   0.0s
[CV] END ....criterion=log_loss, max_depth=50, splitter=best; total time=   0.0s
[CV] END ..criterion=log_loss, max_depth=50, splitter=random; total time=   0.0s
[CV] END ..criterion=log_loss, max_depth=50, splitter=random; total time=   0.0s
[CV] END ..criterion=log_loss, max_depth=50, splitter=random; total time=   0.0s
[CV] END ..criterion=log_loss, max_depth=50, splitter=random; total time=   0.0s
[CV] END ..criterion=log_loss, max_depth=50, splitter=random; total time=   0.0s
[CV] END ..criterion=log_loss, max_depth=None, splitter=best; total time=   0.0s
[CV] END ..criterion=log_loss, max_depth=None, splitter=best; total time=   0.0s
[CV] END ..criterion=log_loss, max_depth=None, splitter=best; total time=   0.0s
[CV] END ..criterion=log_loss, max_depth=None, splitter=best; total time=   0.0s
[CV] END ..criterion=log_loss, max_depth=None, splitter=best; total time=   0.0s
[CV] END criterion=log_loss, max_depth=None, splitter=random; total time=   0.0s
[CV] END criterion=log_loss, max_depth=None, splitter=random; total time=   0.0s
[CV] END criterion=log_loss, max_depth=None, splitter=random; total time=   0.0s
[CV] END criterion=log_loss, max_depth=None, splitter=random; total time=   0.0s
[CV] END criterion=log_loss, max_depth=None, splitter=random; total time=   0.0s

GridSearchCV(cv=5, estimator=DecisionTreeClassifier(),
             param_grid={'criterion': ['gini', 'entropy', 'log_loss'],
                         'max_depth': [10, 50, None],
                         'splitter': ['best', 'random']},
             scoring='accuracy', verbose=2)

In [558]:
print(grid_search.best_score_)
print(grid_search.best_params_)
confusion_matrix(y_test, y_pred)

0.8034208092843096
{'criterion': 'gini', 'max_depth': None, 'splitter': 'best'}

array([[3904, 1309],
       [1318, 5848]], dtype=int64)

In [565]:
all_ratings = []

for ratings in (df['reviews_list']):
    ratings = eval(ratings)
    for score, doc in ratings:
        if score:
            score = score.strip("Rated").strip()
            score = float(score)
            all_ratings.append([score])

KeyError: 'reviews_list'